# [functions]
# included_files = ["node_modules/@img/**/*"]
# external_node_modules = ["sharp"]

[build]
# command = "npm install --platform=linux --arch=x64 sharp@0.32.6 --ignore-engines && npm run build"
command = "rm -rf package-lock.json .node_modules/ && npm install --cpu=x64 --os=linux --libc=glibc sharp@0.32.6 && npm rebuild --verbose sharp && npm run build"
