# [functions]
# included_files = ["node_modules/@img/**/*"]
# external_node_modules = ["sharp"]

[build]
# command = "npm install --platform=linux --arch=x64 sharp@0.32.6 --ignore-engines && npm run build"
# command = "rm -rf package-lock.json .node_modules/ && npm install --ignore-scripts=false --foreground-scripts --verbose --cpu=x64 --os=linux --libc=glibc sharp@0.32.6 && npm rebuild --verbose sharp && npm run build"
# command = "rm -rf package-lock.json .node_modules/ && npm install --ignore-scripts=false --foreground-scripts --verbose --platform=linux --arch=x64 sharp@0.32.6 && npm rebuild --verbose sharp && npm run build"
command = "rm -rf package-lock.json .node_modules/ && npm install --ignore-scripts=false --foreground-scripts --verbose sharp@npm:@img/sharp-linuxmusl-x64 && npm run build"
